// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250711102928_AddGameArtifactName")]
    partial class AddGameArtifactName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxMainStats")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSubStats")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxMainStats = 1,
                            MaxSubStats = 4,
                            Name = "Wuthering Waves"
                        });
                });

            modelBuilder.Entity("API.Models.GameArtifactName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameArtifactNames");
                });

            modelBuilder.Entity("API.Models.GameStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("StatTypeId");

                    b.ToTable("GameStat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Name = "HP%",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            Name = "ATK%",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            Name = "DEF%",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            GameId = 1,
                            Name = "Glacio DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            GameId = 1,
                            Name = "Fusion DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            GameId = 1,
                            Name = "Electro DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            GameId = 1,
                            Name = "Aero DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            GameId = 1,
                            Name = "Spectro DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            GameId = 1,
                            Name = "Havoc DMG Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            GameId = 1,
                            Name = "Energy Regen",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            GameId = 1,
                            Name = "ATK",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            GameId = 1,
                            Name = "Crit. Rate",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            GameId = 1,
                            Name = "Crit. DMG",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            GameId = 1,
                            Name = "Healing Bonus",
                            StatTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            GameId = 1,
                            Name = "HP",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            GameId = 1,
                            Name = "ATK",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 17,
                            GameId = 1,
                            Name = "DEF",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            GameId = 1,
                            Name = "Energy Regen",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            GameId = 1,
                            Name = "Crit. Rate",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            GameId = 1,
                            Name = "Crit. DMG",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            GameId = 1,
                            Name = "ATK%",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            GameId = 1,
                            Name = "DEF%",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            GameId = 1,
                            Name = "HP%",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 24,
                            GameId = 1,
                            Name = "Basic Attack DMG Bonus",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            GameId = 1,
                            Name = "Heavy Attack DMG Bonus",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 26,
                            GameId = 1,
                            Name = "Resonance Skill DMG Bonus",
                            StatTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            GameId = 1,
                            Name = "Resonance Liberation DMG Bonus",
                            StatTypeId = 2
                        });
                });

            modelBuilder.Entity("API.Models.StatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sub"
                        });
                });

            modelBuilder.Entity("API.Models.WuwaMainStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WuwaMainStats");
                });

            modelBuilder.Entity("API.Models.GameArtifactName", b =>
                {
                    b.HasOne("API.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("API.Models.GameStat", b =>
                {
                    b.HasOne("API.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.StatType", "StatType")
                        .WithMany()
                        .HasForeignKey("StatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("StatType");
                });
#pragma warning restore 612, 618
        }
    }
}
