// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519125957_WuwaStatSeedling")]
    partial class WuwaStatSeedling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.WuwaMainStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WuwaMainStats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HP%"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATK%"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DEF%"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Glacio DMG Bonus"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fusion DMG Bonus"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Electro DMG Bonus"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Aero DMG Bonus"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Spectro DMG Bonus"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Havoc DMG Bonus"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Energy Regen"
                        },
                        new
                        {
                            Id = 11,
                            Name = "ATK"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Crit. Rate"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Crit. DMG"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Healing Bonus"
                        });
                });

            modelBuilder.Entity("API.Models.WuwaSubStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WuwaSubStats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HP"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ATK"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DEF"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Energy Regen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crit Rate"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crit DMG"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ATK%"
                        },
                        new
                        {
                            Id = 9,
                            Name = "DEF%"
                        },
                        new
                        {
                            Id = 10,
                            Name = "HP%"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Basic Attack DMG Bonus"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Heavy Attack DMG Bonus"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Resonance Skill DMG Bonus"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Resonance Liberation DMG Bonus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
