services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Backend/API/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
  
  ocr:
    image: ${DOCKER_REGISTRY-}ocr
    build:
      context: ./ocr_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"