services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
        context: .
        dockerfile: Backend/API/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
  
  ocr:
    image: ${DOCKER_REGISTRY-}ocr
    build:
        context: ./ocr_service
        dockerfile: Dockerfile
    ports:
        - "8000:8000"

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
        context: ./react-frontend
        dockerfile: Dockerfile
    ports:
        - "3000:3000"