services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
        context: .
        dockerfile: Backend/API/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    networks:
      - my_network
  
  ocr:
    image: ${DOCKER_REGISTRY-}ocr
    build:
        context: ./ocr_service
        dockerfile: Dockerfile
    ports:
        - "8000:8000"
    networks:
      - my_network

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
        context: ./react-frontend
        dockerfile: Dockerfile
    volumes:
        - ./react-frontend:/app
        - /app/node_modules
    ports:
        - "3000:3000"
    environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true
        - WDS_SOCKET_PORT=3000
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
